### ISSUE TITLE
Bundle without Js file 

### ISSUE THREAD

**Issue by mmezzawi** [ischenko/yii2-jsloader-requirejs#1]
When having a Assets A that depend on Assets B and asset B only css ( Js array is empty ) or all assets files belong of B to a position that you don't wan't to import ( importJsFilesFromBundle )  , the requireJs function dependency array will contain value for a module that doesn't have any js file which will cause a require js to load the path+'.js'

**_output of configuration object ;_**
var require = {"paths":{"yii\validators\ValidationAsset":["/web/assets/9dd469f5/yii.validation"],"yii\web\YiiAsset":["/web/assets/9dd469f5/yii"],"yii\web\JqueryAsset":["/web/assets/854a9212/jquery"],"yii\widgets\ActiveFormAsset":["/web/assets/9dd469f5/yii.activeForm"],"app\assets\AppAsset":["/web/js/common/common"],"yii\bootstrap\BootstrapAsset":["/web/assets/b2eba9b5/js/bootstrap"],"app\assets\ErrorAsset":"/web","app\assets\....
.....
"app\assets\BootstrapAsset":{"deps":["yii\web\YiiAsset",""app\assets\ErrorAsset","app\

_**output of the jscode ( publishRequireJs )**_ 

require(["yii\validators\ValidationAsset","yii\web\YiiAsset","yii\web\JqueryAsset","yii\widgets\ActiveFormAsset","app\assets\AppAsset","yii\bootstrap\BootstrapAsset"], function() {
.... js code here ....

So as you can notice , while requirejs is trying to load BootstrapAsset module dependency , it will try to load ErrorAsset , which is causing the js issue

**Comment by ischenko** [comment]
@mmezzawi thanks for reporting. This issue is in my TODO list, since I faced with it too. 
As a workaround you can add such bundles into ignore list:

``` php
                'loader' => [
                    'class' => 'ischenko\yii2\jsloader\RequireJs',
                    'ignoreBundles' => [
                        'app\assets\ErrorAsset'
                    ]
                ]
```

Please note that the extension is still in development and not ready yet for production use.

**Comment by mmezzawi** [comment]
Dear @ischenko  , 
you are doing a great job with this extension. 
I have a question about the fix, why we should loop over dependency inside the addDependency , isn't that done in the recursive call of registerAssetBundle?

Another note : if the main is null the js file is published to each user which mean we will have billion of assets folder in just 1 week. Are you planning to handle that ?
Thanks.

**Comment by mmezzawi** [comment]
@ischenko , can you please upload this package to packagist so we can install it via composer :+1:

**Comment by ischenko** [comment]
@mmezzawi 

> I have a question about the fix, why we should loop over dependency inside the addDependency , isn't that done in the recursive call of registerAssetBundle?

We can't just remove dependency without files. For example, we have Assets A that depends from B (css only) and B depends on C and D. Removal of assets B might break JS code. So this fix will remove B from the assets chain and attach C and D directly to A. I agree that this particular implementation might require some optimization. I added this into TODO and will return to this later.

> Another note : if the main is null the js file is published to each user which mean we will have billion of assets folder in just 1 week. Are you planning to handle that ?

Thanks. I've added a quick-fix for it for now.

**Comment by ischenko** [comment]
@mmezzawi , added to packagist
